### ISSUE TITLE
Options from VSCode extension

### ISSUE THREAD

**Issue by giannif** [angryobject/react-pure-to-class#10]
I'd like to use the [reactComponent](https://github.com/angryobject/react-pure-to-class/blob/d705b9e2d43f2f602e154f2a291906c5ea44c2d5/packages/react-pure-to-class/pure-to-class.js#L6) option in VSCode. Is there any way to do that? Perhaps in VSCode `User Settings`?   

Something like?
```javascript
"reactPureToClass.reactComponent": "PureComponent"

**Comment by angryobject** [comment]
Yeah, I'll look into it!

**Comment by angryobject** [comment]
Done in 1.1.7
