### ISSUE TITLE
Add option to destructure props differently 

### ISSUE THREAD

**Issue by tgreen7** [angryobject/react-pure-to-class#3]
It destructures props to this:
```
const {
    props: { error }
} = this;
```
Whereas I usually would do this:
```
const {
    error
} = this.props;
```

maybe provide a preference setting to specify whether you want to destructure this or this.props?

Also I rarely use the constructor so if there was an option to leave that off as well that would be awesome!

Thanks!

**Comment by angryobject** [comment]
Well, I'll look into this once I have time.

Regarding destructuring, it's done this way because you there this two main cases:

```javascript
function MyComponent(props) {}
function MyComponent({ prop1, prop2 }) {}
```

And simply destructuring those function arguments on `this` is a more general case. But destructuring `this.props` looks nicer, I agree. I'll look what I can do.

**Comment by angryobject** [comment]
Should be better now, I changed the destructuring behaviour
