### ISSUE TITLE
Support for typescript files

### ISSUE THREAD

**Issue by GabeDuarteM** [angryobject/react-pure-to-class#6]
Currently, if i open a tsx file (typescript react) and try to use the extension, it gives me a message saying "Only available for javascript/react file types". 

It would be nice to have support for typescript files as well...

What do you think?

**Comment by angryobject** [comment]
Check this https://github.com/angryobject/react-pure-to-class/pull/2 please.

For me it's easy to enable it for `ts` files, but there's no guarantee it'll work correctly.

**Comment by GabeDuarteM** [comment]
Hmm, I see (sorry for not checking that earlier),

Maybe we could test it, and if it behaves mostly fine, it could be enabled as an experimental feature, enabled at the settings...

I think this is a very productive plugin, and not being able to use it on ts files is kind of a bummer for me, as most of my projects use typescript.

**Comment by angryobject** [comment]
Yes, that's a possibility. But i'm not familiar with TS myself so i don't know any usecases for it and can't write tests. 

But i just thought may be i can just add this checkbox in settings, like "enable for TS files (might not work correctly, officially not supported)". Will see.

**Comment by angryobject** [comment]
You can now set `reactPureToClass.typescript` setting to `true` to enable ts files support. But it comes with no guarantees =)

**Comment by GabeDuarteM** [comment]
I swear I thought I had replied here, but apparently, I didn't, sorry about that.

Thank you for adding that setting!
