### ISSUE TITLE
Syntax when transforming arrow-functions

### ISSUE THREAD

**Issue by larsnystrom** [angryobject/react-pure-to-class#8]
First of all, thank you for this plugin, I use it extensively!

I'm experiencing what's being discussed in #4, but I understand that this is not an error but a deliberate choice.

The thing is though that I'm maintaining a fairly large app where all stateless functions are written in the the form

```js
const MyComp = () => <div/>
MyComp.propTypes = {}
export default MyComp
```

I use this plugin by selecting `const MyComp = () => <div/>` and then running the pure to class command. The result is `const MyComp = class extends React.Component { ... }`, as discussed in #4.

But since I'm also using eslint with `react/recommended` enabled, the entire component fails linting after doing this, forcing me to manually change `const MyComp = class extends ...` into `class MyComp extends ...` every time, for every component I'm doing this on.

I realize it might be safer to convert into the current `const MyComp = class extends...` syntax, but would it be possible to at least provide an option to instead convert it into `class MyComp extends ...` instead?

Actually, I was even thinking that in this case, where the component is an arrow function and the selection includes an assignment of this arrow function on a constant, perhaps it could even be standard to convert it into `class MyComp extends` instead? Since arrow functions can't have names, we can be certain that the name of the constant is the name of the component. 

What do you think?

**Comment by angryobject** [comment]
Well, I think i need to explore it a bit) Actually, i agree that It makes sense to do it this way in case of arrow functions. I'll let you know when i have any progress on this.

**Comment by angryobject** [comment]
Just a quick heads-up. I'm quite busy on work these days, but today i managed to make a draft version of this functionality and it seems to work fine. I'll try to release the new version next week.

**Comment by angryobject** [comment]
Done in d705b9e2d43f2f602e154f2a291906c5ea44c2d5
